name: NestJS API CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/api-docker.ci.yml'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check out repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.REGISTRY_TOKEN }}
          fetch-depth: 0
          
      # - name: Run e2e tests
      #   run: docker compose -f docker-compose.ci.yaml --env-file env-example -p ci up --build --exit-code-from api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_BACKEND }}" > ./backend/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64 # Add this line for multi-platform build
          tags: ghcr.io/preppe/audiobook/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
